name: Validate

on:
    push:
        branches: [ main ]
        paths:
            - '.github/workflows/validate.yaml'
            - 'schemas/*.json'
            - 'games/*.yaml'
    pull_request:
        branches: [ main ]
        paths:
            - '.github/workflows/validate.yaml'
            - 'schemas/*.json'
            - 'games/*.yaml'

env:
    NODE_VERSION: 18

jobs:
    validate-schema:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install
              run: |
                  npm ci
                  npm install

            - name: Validate Schema
              run: npm run compile

    validate-games:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install
              run: |
                  npm ci
                  npm install

            - name: Validate
              run: npm run validate
